/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoubanListRouteImport } from './routes/douban/list'
import { Route as DoubanDetailIdRouteImport } from './routes/douban/detail.$id'
import { Route as DoubanApiListRouteImport } from './routes/douban/api.list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubanListRoute = DoubanListRouteImport.update({
  id: '/douban/list',
  path: '/douban/list',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubanDetailIdRoute = DoubanDetailIdRouteImport.update({
  id: '/douban/detail/$id',
  path: '/douban/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubanApiListRoute = DoubanApiListRouteImport.update({
  id: '/douban/api/list',
  path: '/douban/api/list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/douban/list': typeof DoubanListRoute
  '/douban/api/list': typeof DoubanApiListRoute
  '/douban/detail/$id': typeof DoubanDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/douban/list': typeof DoubanListRoute
  '/douban/api/list': typeof DoubanApiListRoute
  '/douban/detail/$id': typeof DoubanDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/douban/list': typeof DoubanListRoute
  '/douban/api/list': typeof DoubanApiListRoute
  '/douban/detail/$id': typeof DoubanDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/douban/list' | '/douban/api/list' | '/douban/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/douban/list' | '/douban/api/list' | '/douban/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/douban/list'
    | '/douban/api/list'
    | '/douban/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoubanListRoute: typeof DoubanListRoute
  DoubanApiListRoute: typeof DoubanApiListRoute
  DoubanDetailIdRoute: typeof DoubanDetailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douban/list': {
      id: '/douban/list'
      path: '/douban/list'
      fullPath: '/douban/list'
      preLoaderRoute: typeof DoubanListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douban/detail/$id': {
      id: '/douban/detail/$id'
      path: '/douban/detail/$id'
      fullPath: '/douban/detail/$id'
      preLoaderRoute: typeof DoubanDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douban/api/list': {
      id: '/douban/api/list'
      path: '/douban/api/list'
      fullPath: '/douban/api/list'
      preLoaderRoute: typeof DoubanApiListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoubanListRoute: DoubanListRoute,
  DoubanApiListRoute: DoubanApiListRoute,
  DoubanDetailIdRoute: DoubanDetailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
